patched version.sh and godebug and bumppatch

diff --git a/bin/bumppatch b/bin/bumppatch
--- a/bin/bumppatch
+++ b/bin/bumppatch
@@ -43,9 +43,9 @@ function so()
 # always show such a message.  If known terminal, print the message
 # in reverse video mode. This is the other way, not using escape sequences
 {
-   [ "$1" != on -a "$1" != off ] && return 
+   [ "$1" != on -a "$1" != off ] && return
     if [ "$TERM" = xterm -o "$TERM" = vt100 -o "$TERM" = xterm-256color  -o "$TERM" = screen ] ; then
-      [ "$1" = on ] && tput smso 
+      [ "$1" = on ] && tput smso
       [ "$1" = off ] && tput rmso
     fi
 }
@@ -72,7 +72,7 @@ function colBlink()     { printf "\e[5m"; return 0; }
 
 # --- Exits
 
-# function error()        { err 'ERROR:' $*; return 0; } # similar to err but with ERROR prefix and possibility to include 
+# function error()        { err 'ERROR:' $*; return 0; } # similar to err but with ERROR prefix and possibility to include
 # Write an error message to stderr. We cannot use err here as the spaces would be removed.
 function error()        { so on; echo 'ERROR:'$* 1>&2;            so off ; return 0; }
 function error4()       { so on; echo 'ERROR:    '$* 1>&2;        so off ; return 0; }
@@ -110,7 +110,7 @@ function parseCLI() {
     local currentOption
     while getopts "Dnvh" options; do         # Loop: Get the next option;
         case "${options}" in                    # TIMES=${OPTARG}
-            D)  err Debug enabled ; debugSet     
+            D)  err Debug enabled ; debugSet
                 ;;
             n)  dry=echo
                 debug dry mode enabled
@@ -150,21 +150,21 @@ function usage()
 
 function main() {
     exitIfBinariesNotFound pwd tput basename dirname  bumpversion version.sh
-    parseCLI $* 
+    parseCLI $*
     shift $(($OPTIND - 1))  # not working inside parseCLI
     debug args are $*
     # --------------------
     # nice idea to change to the git root directory and start commands from there. But, some git solutions might
     # contain multiple projects. So, let's expect, that the file to be upgraded is in the current directory.
     # Another advantage is that the command can be used for development which are not under git.
-    #_gitRootDir=$(git rev-parse --show-toplevel 2>/dev/null); res=$? 
+    #_gitRootDir=$(git rev-parse --show-toplevel 2>/dev/null); res=$?
     #[ $res -eq 0 ] && debug git found, jumping to git root && cd "$_gitRootDir"
 
     _calcVersion=$(version.sh)
     [ -z $_calcVersion ] && errorExit 1 $app could not determine the version using version.sh
     debug Existing version is $_calcVersion
-    verbosenl bumpversion --current-version $_calcVersion --allow-dirty ${CMD} $(version.sh -d | cut -d: -f1)
-    $dry bumpversion --current-version $_calcVersion --allow-dirty ${CMD} $(version.sh -d | cut -d: -f1)
+    verbosenl bumpversion --current-version $_calcVersion --allow-dirty ${CMD} $(version.sh -v | cut -d: -f1)
+    $dry bumpversion --current-version $_calcVersion --allow-dirty ${CMD} $(version.sh -v | cut -d: -f1)
     debug New version is $(version.sh)
 }
 
