Major pass of shellcheck for all commands. Rewrite bigger commands in more minimal form, do proper command-line parsing, esp. for namespace.

diff --git a/bin/k8cp b/bin/k8cp
--- a/bin/k8cp
+++ b/bin/k8cp
@@ -1,160 +1,66 @@
 #!/usr/bin/env bash
-# vim: set expandtab: ts=3: sw=3
-#
-# TITLE: $_app
-#
-# DESCRIPTION: <see usage function below>
-#
-# LICENSE: MIT todo
-#
-# Permission is hereby granted, free of charge, to any person obtaining a copy of this
-# software and associated documentation files (the "Software"), to deal in the Software
-# without restriction, including without limitation the rights to use, copy, modify, merge,
-# publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
-# to whom the Software is furnished to do so, subject to the following conditions:
-#
-# The above copyright notice and this permission notice shall be included in all copies
-# or substantial portions of the Software.
-#
-# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
-# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
-# PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
-# FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
-# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
-#
 
-#########################################################################################
-# VARIABLES, CONSTANTS
+[ -z "$KUBECTL" ] && echo >&2 "KUBECTL environment variable is not set, exiting" && exit 1
 
-readonly _app=$(basename $0)
-readonly _appDir=$(dirname $0)
-readonly _absoluteAppDir=$(cd $_appDir; /bin/pwd)
-readonly _appVersion="1.0.0" # use semantic versioning
-export DebugFlag=${DebugFlag:-FALSE}
+## cmdline parsing
+declare -a other_opts=()
+declare -a ns=()
+declare -a container=()
+while [[ $# -gt 0 ]]; do
+    case "$1" in
+    -c | --container)
+        container=("-c" "$2")
+        shift 2
+        ;;
+    -n | --namespace)
+        ns=("-n" "$2")
+        shift 2
+        ;;
+    *)
+        other_opts+=("$1") # save positional arg
+        shift
+        ;;
+    esac
+done
 
-#########################################################################################
+declare -a cmd_to_exec=("$KUBECTL" "${ns[@]}" "cp")
 
-# --- debug: Conditional debugging. All commands begin w/ debug.
+[ "${#other_opts[@]}" -eq 0 ] && echo >&2 "ERROR: no pod name given" && exit 2
+[ "${#other_opts[@]}" -eq 1 ] && echo >&2 "ERROR: only source of copy given" && exit 3
+[ "${#other_opts[@]}" -ge 3 ] && echo >&2 "ERROR: currently only 1 source and 1 destination are supported" && exit 4
+# Check whether one of source or dest looks like a unique-pod-spec (which contains a colon, pod:file)
+! echo "${other_opts[0]}" | grep -q ':' &>/dev/null &&
+    ! echo "${other_opts[1]}" | grep -q ':' &>/dev/null &&
+    echo >&2 "ERROR: neither source nor destination look like unique-pod-specs (one of them should contain a colon ':'): ${other_opts[*]}" &&
+    exit 5
+# Check whether both source and dest contain a unique-pod-spec
+echo "${other_opts[0]}" | grep -q ':' &>/dev/null &&
+    echo "${other_opts[1]}" | grep -q ':' &>/dev/null &&
+    echo >&2 "ERROR: BOTH source and destination look like unique-pod-specs (both of them contains a colon ':'): ${other_opts[*]}" &&
+    exit 6
 
-function debugSet()             { DebugFlag=TRUE; return 0; }
-function debugUnset()           { DebugFlag=; return 0; }
-function debug()                { [ "$DebugFlag" = TRUE ] && echo 'DEBUG:'$* 1>&2 ; return 0; }
-function debug4()               { [ "$DebugFlag" = TRUE ] && echo 'DEBUG:    ' $* 1>&2 ; return 0; }
-function debug8()               { [ "$DebugFlag" = TRUE ] && echo 'DEBUG:        ' $* 1>&2 ; return 0; }
-function debug12()              { [ "$DebugFlag" = TRUE ] && echo 'DEBUG:            ' $* 1>&2 ; return 0; }
+declare src="${other_opts[0]}"
+declare dest="${other_opts[1]}"
+_pod=
+if [[ "$src" = *:* ]]; then
+    _pod="$($KUBECTL "${ns[@]}" get pod | grep -i "${src%:*}" | awk '{ print $1; }')"
+    [ "$(echo "$_pod" | wc -l)" -gt 1 ] && echo >&2 -e "ERROR: too many pods matched:\n$_pod" && exit 7
+    [ "$_pod" = '' ] || [ -z "${_pod+x}" ] && {
+        echo >&2 "ERROR: no pods matched with: ${src%:*}"
+        exit 8
+    }
+    # kubectl cp doesn't like '.' as destination, and messes up big time
+    [ "$dest" = '.' ] && dest="$(realpath "$dest")/$(basename "$src")"
+    cmd_to_exec+=("$_pod:${src#*:}" "$dest" "${container[@]}")
+else
+    _pod="$($KUBECTL "${ns[@]}" get pod | grep -i "${dest%:*}" | awk '{ print $1; }')"
+    [ "$(echo "$_pod" | wc -l)" -gt 1 ] && echo >&2 -e "ERROR: too many pods matched:\n$_pod" && exit 9
+    [ "$_pod" = '' ] || [ -z "${_pod+x}" ] && {
+        echo >&2 "ERROR: no pods matched with: ${dest%:*}"
+        exit 10
+    }
+    cmd_to_exec+=("$src" "$_pod:${dest#*:}" "${container[@]}")
+fi
 
-# --- Exits
-
-# function error()        { err 'ERROR:' $*; return 0; } # similar to err but with ERROR prefix and possibility to include
-# Write an error message to stderr. We cannot use err here as the spaces would be removed.
-function error()        { echo 'ERROR:'$* 1>&2;             return 0; }
-function error4()       { echo 'ERROR:    '$* 1>&2;         return 0; }
-function error8()       { echo 'ERROR:        '$* 1>&2;     return 0; }
-function error12()      { echo 'ERROR:            '$* 1>&2; return 0; }
-
-function errorExit()    { EXITCODE=$1 ; shift; error $* ; exit $EXITCODE; }
-function exitIfErr()    { a="$1"; b="$2"; shift; shift; [ "$a" -ne 0 ] && errorExit $b App returned $a $*; }
-
-function err()          { echo $* 1>&2; }                 # just write to stderr
-function err4()         { echo '   ' $* 1>&2; }           # just write to stderr
-function err8()         { echo '       ' $* 1>&2; }       # just write to stderr
-function err12()        { echo '           ' $* 1>&2; }   # just write to stderr
-
-# --- Existance checks
-function exitIfBinariesNotFound()       { for file in $@; do [ $(command -v "$file") ] || errorExit 253 binary not found: $file; done }
-function exitIfPlainFilesNotExisting()  { for file in $*; do [ ! -f $file ] && errorExit 254 'plain file not found:'$file 1>&2; done }
-function exitIfFilesNotExisting()       { for file in $*; do [ ! -e $file ] && errorExit 255 'file not found:'$file 1>&2; done }
-function exitIfDirsNotExisting()        { for dir in $*; do [ ! -d $dir ] && errorExit 252 "$APP:ERROR:directory not found:"$dir; done }
-
-# --- Temporary file/directory  creation
-# -- file creation -- TMP1=$(tempFile); TMP2=$(tempFile) ;;;; trap "rm -f $TMP1 $TMP2" EXIT
-# -- directory creation -- TMPDIR=$(tempDir) ;;;;;  trap "rm -fr $TMPDIR;" EXIT
-#
-function tempFile()                     { mktemp ${TMPDIR:-/tmp/}$_app.XXXXXXXX; }
-function tempDir()                      { mktemp -d "${TMPDIR:-/tmp/}$_app.YYYYYYYYY"; }
-# realpath as shell, argument either supplied as stdin or as $1
-
-# application-specific functions  ===============================================================================
-
-function usage()
-{
-    err DESCRIPTION
-    err
-    err4 k8cp program to copy files to/from a pod
-    err
-    err SYNOPSIS
-    err4 $_app '[-D] [-c <container>] [-n <namespace>] <uniquePodSpec>:file file'
-    err4 $_app '[-D] [-c <container>] [-n <namespace>] file <uniquePodSpec>:file'
-    err4 $_app '-h'
-    err
-    err VERSION
-    err4 $_appVersion
-    err
-    err OPTIONS
-    err4 '-n <namespace>'
-    err4 '-c <container>'
-    err4 '-D      ::= enable debug output'
-    err4 '-h      ::= show usage message and exit with 1'
-    err4 todo .......
-}
-
-# exit codes 1..9
-function parseCLI() {
-    local currentOption
-    while getopts "Dn:hc:" options; do         # Loop: Get the next option;
-        case "${options}" in                    # TIMES=${OPTARG}
-            D)  err Debug enabled ; set -x ; debugSet
-                ;;
-            n)  debug namespace explicitly set
-                _namespace="-n $OPTARG"
-                ;;
-            c)  debug container is $OPTARG
-                _container="-c $OPTARG"
-                ;;
-            h)  usage ; exit 1
-                ;;
-            *)
-                errorExit 2 Wrong argument supplied. Help with $_app -h
-                ;;
-        esac
-    done
-}
-
-function findPod() {
-    if [ "$DebugFlag" = TRUE ] ; then
-        err in debug mode, returning fixed pod name demopod
-        echo demopod
-    else
-        local _pod=$($KUBECTL get pod $_namespace -o name | egrep -E -i "$1" | cut -d ' ' -f 1);
-        [[ $(echo $_pod | wc -l) -ne 1 ]] && errorExit 10 not exactly one pod could be identified
-        echo $_pod | sed -E -e 's,^pod/,,'
-    fi
-    return 0
-}
-
-function main() {
-    exitIfBinariesNotFound pwd basename dirname mktemp $KUBECTL egrep cut wc sed
-    parseCLI $*
-    shift $(($OPTIND - 1))  # not working inside parseCLI
-    myArray=( $* ) # move all arguments into an array
-
-    count=0
-    for ar in ${myArray[*]} ; do # for all arguments supplied
-        debug count is $count
-        if [[ $ar =~ : ]] ; then
-            debug matching on $ar
-            _match=$(echo $ar | sed -E -e 's/:.*//')
-            _rest=$(echo $ar| sed -E -e  's/.*://')
-            myArray[$count]=$(findPod $_match):$_rest
-        else
-            debug working in argument $count, not matching
-        fi
-        (( count += 1 ))
-    done
-    echo kubectl cp  $_container $_namespace ${myArray[*]}
-    kubectl cp  $_container $_namespace ${myArray[*]}
-}
-
-main $*
-
-# EOF
+set -x
+"${cmd_to_exec[@]}"
diff --git a/bin/k8exec b/bin/k8exec
--- a/bin/k8exec
+++ b/bin/k8exec
@@ -1,35 +1,51 @@
 #!/usr/bin/env bash
-# shellcheck disable=SC2155
-
-function err()          { echo "$*" 1>&2; }                 # just write to stderr
-function err4()         { echo '   ' "$*" 1>&2; }           # just write to stderr
-function err8()         { echo '       ' "$*" 1>&2; }       # just write to stderr
-function err12()        { echo '           ' "$*" 1>&2; }   # just write to stderr
-
-# function error()        { err 'ERROR:' $*; return 0; } # similar to err but with ERROR prefix and possibility to include
-# Write an error message to stderr. We cannot use err here as the spaces would be removed.
-function error()        { echo 'ERROR:'"$*" 1>&2;             return 0; }
-function error4()       { echo 'ERROR:    '"$*" 1>&2;         return 0; }
-function error8()       { echo 'ERROR:        '"$*" 1>&2;     return 0; }
-function error12()      { echo 'ERROR:            '"$*" 1>&2; return 0; }
-
-function errorExit()    { EXITCODE="$1" ; shift; error "$*" ; exit "$EXITCODE"; }
 
 ## k8exec just requires a unique part of the pod-name in the given or the default namespace
+## options (all optional):
+## -n namespace
+##
 ## options: -n namespace
 ## arguments, optional: command, default: /bin/bash
 
-[ -z "$KUBECTL" ] && errorExit 1 KUBECTL is not defined
+[ -z "$KUBECTL" ] && echo >&2 "KUBECTL environment variable is not set, exiting" && exit 1
 
-_namespace=""
-[ "$1" = '-n' -o "$1" = '--namespace' ] && shift && _namespace="-n $1" && shift;
+## cmdline parsing
+declare -a other_opts=()
+declare -a ns=()
+while [[ $# -gt 0 ]]; do
+    case "$1" in
+    -n | --namespace)
+        # This is only parsed if it's the first non-positional arg
+        # because if it's after the first positional arg, it may well be
+        # an option for the command in the container
+        if [ "${#other_opts[@]}" -eq 0 ]; then
+            ns=("-n" "$2")
+            shift 2
+        fi
+        ;;
+    *)
+        other_opts+=("$1") # save positional arg
+        shift
+        ;;
+    esac
+done
 
-_pod=$($KUBECTL get pod "$_namespace" -o name | grep -i "$1" | cut -d ' ' -f 1);
-shift;
+declare -a cmd_to_exec=("$KUBECTL")
 
-cmd=;
-[ "$*" = "" ] && cmd=/bin/bash;
+[ "${#other_opts[@]}" -eq 0 ] && echo >&2 "ERROR: no pod name given" && exit 2
+# default to 'bash' with 1 positional arg (pod name)
+[ "${#other_opts[@]}" -eq 1 ] && other_opts+=("bash")
 
-$KUBECTL exec "$_namespace" -it "$_pod" -- "$cmd" "$@"
+_pod="$($KUBECTL "${ns[@]}" get pod | grep -i "${other_opts[0]}" | awk '{ print $1; }')"
+[ "$(echo "$_pod" | wc -l)" -gt 1 ] && echo >&2 -e "ERROR: too many pods matched:\n$_pod" && exit 3
+[ "$_pod" = '' ] || [ -z "${_pod+x}" ] && {
+    echo >&2 "ERROR: no pods matched with: ${other_opts[0]}"
+    exit 4
+}
 
-# EOF
+# Add to command to execute:
+# exec -n<ns> -it <pod_name> <other_opts>
+cmd_to_exec+=("exec" "${ns[@]}" "-it" "$_pod" "${other_opts[@]:1}")
+
+set -x
+"${cmd_to_exec[@]}"
diff --git a/bin/k8logs b/bin/k8logs
--- a/bin/k8logs
+++ b/bin/k8logs
@@ -1,34 +1,43 @@
 #!/usr/bin/env bash
-# shellcheck disable=SC2155
-
-function err()          { echo "$*" 1>&2; }                 # just write to stderr
-function err4()         { echo '   ' "$*" 1>&2; }           # just write to stderr
-function err8()         { echo '       ' "$*" 1>&2; }       # just write to stderr
-function err12()        { echo '           ' "$*" 1>&2; }   # just write to stderr
-
-# function error()        { err 'ERROR:' $*; return 0; } # similar to err but with ERROR prefix and possibility to include
-# Write an error message to stderr. We cannot use err here as the spaces would be removed.
-function error()        { echo 'ERROR:'"$*" 1>&2;             return 0; }
-function error4()       { echo 'ERROR:    '"$*" 1>&2;         return 0; }
-function error8()       { echo 'ERROR:        '"$*" 1>&2;     return 0; }
-function error12()      { echo 'ERROR:            '"$*" 1>&2; return 0; }
-
-function errorExit()    { EXITCODE="$1" ; shift; error "$*" ; exit "$EXITCODE"; }
 
 ## k8exec just requires a unique part of the pod-name in the given or the default namespace
 ## options: -n namespace
 ## arguments, optional: command, default: /bin/bash
 
-[ -z "$KUBECTL" ] && errorExit 1 KUBECTL is not defined
+[ -z "$KUBECTL" ] && echo >&2 "KUBECTL environment variable is not set, exiting" && exit 1
 
-## k8logs just requires a unique part of the pod-name. -f can be specified.
-## options: -f
-_namespace=""
-follow=
-[ "$1" = -f ] && shift && follow=-f
-[ "$1" = '-n' -o "$1" = '--namespace' ] && shift && _namespace="-n $1" && shift
-[ "$1" = -f ] && shift && follow=-f
-_pod=$($KUBECTL get po "$_namespace" | grep -i "$1" | cut -d ' ' -f 1)
-$KUBECTL logs "$_namespace" "$follow" "$_pod"
+## cmdline parsing
+declare -a other_opts=()
+declare -a ns=()
+declare follow=0
+while [[ $# -gt 0 ]]; do
+    case "$1" in
+    -f)
+        follow=1
+        shift
+        ;;
+    -n | --namespace)
+        ns=("-n" "$2")
+        shift 2
+        ;;
+    *)
+        other_opts+=("$1") # save positional arg
+        shift
+        ;;
+    esac
+done
 
-# EOF
+declare -a cmd_to_exec=("$KUBECTL" "logs" "${ns[@]}")
+[ "$follow" -eq 1 ] && cmd_to_exec+=("-f")
+
+_pod="$($KUBECTL "${ns[@]}" get pod | grep -i "${other_opts[0]}" | awk '{ print $1; }')"
+[ "$(echo "$_pod" | wc -l)" -gt 1 ] && echo >&2 -e "ERROR: too many pods matched:\n$_pod" && exit 2
+
+# add pod name, first positional arg is expected to be the pod name
+cmd_to_exec+=("$($KUBECTL "${ns[@]}" get pod | grep -i "${other_opts[0]}" | awk '{ print $1; }')")
+
+# add rest of positional args (WITHOUT the first: the pod substring)
+cmd_to_exec+=("${other_opts[@]:1}")
+
+set -x
+"${cmd_to_exec[@]}"
