md2pdf changed to sourced lib, mdSlides2PDF ⟺  marp2pdf, new bash.mini.skeleton.sh add of Version number -V option

diff --git a/bin/md2pdf b/bin/md2pdf
--- a/bin/md2pdf
+++ b/bin/md2pdf
@@ -27,59 +27,20 @@
 #########################################################################################
 # VARIABLES, CONSTANTS
 
-_app=$(basename "${0}")
-declare -r _app
-_appDir=$(dirname "$0")
-declare -r _appDir
-_absoluteAppDir=$(cd "$_appDir" || exit 99 ; /bin/pwd)
-declare -r _absoluteAppDir
-_appVersion="0.0.1"      # use semantic versioning
-declare -r _appVersion
-export DebugFlag=${DebugFlag:-FALSE}
+#########################################################################################
+readonly _app="$(basename $0)"
+readonly _appDir="$(dirname $0)"
+readonly _appVersion="0.0.3" # use semantic versioning
 
 #########################################################################################
+# ConfigShell lib 1.1 (codebase 1.0.0)
+bashLib="/opt/ConfigShell/lib/bashlib.sh"
+[ ! -f "$bashLib" ] && 1>&2 echo "bash-library $bashLib not found" && exit 127
+# shellcheck source=/opt/ConfigShell/lib/bashlib.sh
+source "$bashLib"
+unset bashLib
 
-# --- debug: Conditional debugging. All commands begin w/ debug.
-
-function debugSet()             { DebugFlag=TRUE; return 0; }
-function debugUnset()           { DebugFlag=; return 0; }
-function debugExecIfDebug()     { [ "$DebugFlag" = TRUE ] && "$*"; return 0; }
-function debug()                { [ "$DebugFlag" = TRUE ] && echo 'DEBUG:'"$*" 1>&2 ; return 0; }
-function debug4()               { [ "$DebugFlag" = TRUE ] && echo 'DEBUG:    ' "$*" 1>&2 ; return 0; }
-function debug8()               { [ "$DebugFlag" = TRUE ] && echo 'DEBUG:        ' "$*" 1>&2 ; return 0; }
-function debug12()              { [ "$DebugFlag" = TRUE ] && echo 'DEBUG:            ' "$*" 1>&2 ; return 0; }
-
-# --- Exits
-
-# function error()        { err 'ERROR:' $*; return 0; } # similar to err but with ERROR prefix and possibility to include
-# Write an error message to stderr. We cannot use err here as the spaces would be removed.
-function error()        { echo 'ERROR:'"$*" 1>&2;             return 0; }
-function error4()       { echo 'ERROR:    '"$*" 1>&2;         return 0; }
-function error8()       { echo 'ERROR:        '"$*" 1>&2;     return 0; }
-function error12()      { echo 'ERROR:            '"$*" 1>&2; return 0; }
-
-function errorExit()    { EXITCODE="$1" ; shift; error "$*" ; exit "$EXITCODE"; }
-function exitIfErr()    { a="$1"; b="$2"; shift; shift; [ "$a" -ne 0 ] && errorExit "$b" App returned "$a" "$*"; }
-
-function err()          { echo "$*" 1>&2; }                 # just write to stderr
-function err4()         { echo '   ' "$*" 1>&2; }           # just write to stderr
-function err8()         { echo '       ' "$*" 1>&2; }       # just write to stderr
-function err12()        { echo '           ' "$*" 1>&2; }   # just write to stderr
-
-# --- Existance checks
-function exitIfBinariesNotFound()       { for file in "$@"; do command -v "$file" || errorExit 253 binary not found: "$file" ; done }
-function exitIfPlainFilesNotExisting()  { for file in "$@"; do [ ! -f "$file" ] && errorExit 254 'plain file not found:'"$file" 1>&2; done }
-function exitIfFilesNotExisting()       { for file in "$@"; do [ ! -e "$file" ] && errorExit 255 'file not found:'"$file" 1>&2; done }
-function exitIfDirsNotExisting()        { for dir in "$@"; do [ ! -d "$dir" ] && errorExit 252 "$APP:ERROR:directory not found:$dir"; done }
-
-# --- Temporary file/directory  creation
-# -- file creation -- TMP1=$(tempFile); TMP2=$(tempFile) ;;;; trap "rm -f $TMP1 $TMP2" EXIT
-# -- directory creation -- TMPDIR=$(tempDir) ;;;;;  trap "rm -fr $TMPDIR;" EXIT
-#
-function tempFile()                     { mktemp "${TMPDIR:-/tmp/}$_app.XXXXXXXX"; }
-function tempDir()                      { mktemp -d "${TMPDIR:-/tmp/}$_app.YYYYYYYYY"; }
-# realpath as shell, argument either supplied as stdin or as $1
-
+#########################################################################################
 # application-specific functions  ===============================================================================
 
 function usage()
@@ -90,6 +51,7 @@ function usage()
     err
     err SYNOPSIS
     err4 "$_app" '[-D] [-f] [dir...]'
+    err4 "$_app" '-V'
     err4 "$_app" '-h'
     err
     err VERSION
@@ -97,14 +59,17 @@ function usage()
     err
     err OPTIONS
     err4 '-D      ::= enable debug output'
+    err4 '-V      ::= output the version number and exit with code 127'
     err4 '-h      ::= show usage message and exit with exit code 1'
     err4 '-f      ::= overwrite if output file already exists'
 }
 
 function parseCLI() {
-    while getopts "Dfh" options; do         # Loop: Get the next option;
+    while getopts "DVfh" options; do         # Loop: Get the next option;
         case "${options}" in                    # TIMES=${OPTARG}
             D)  err Debug enabled ; debugSet
+                ;;
+            V)  1>&2 echo $_appVersion ; exit 127
                 ;;
             f)  debug forcedMode; forcedMode=TRUE
                 ;;
@@ -132,8 +97,8 @@ function main() {
         [ -f "$outfile" ] && [ "$forcedMode" != TRUE ] && errorExit 10 Output file "$outfile" already existing, not overwriting.
         header=
         [ -f latex.tex ] && debug including latex.tex to command && header="-H latex.tex"
-        debug pandoc --listings $header -H /opt/ConfigShell/share/Markdown-Document/listing-ssetup.tex -o "$outfile" "$file"
-        pandoc --listings $header -H /opt/ConfigShell/share/Markdown-Document/listing-ssetup.tex -o "$outfile" "$file"
+        debug pandoc --pdf-engine=xelatex --listings $header -H /opt/ConfigShell/share/Markdown-Document/listing-ssetup.tex -o "$outfile" "$file"
+        pandoc --pdf-engine=xelatex --listings $header -H /opt/ConfigShell/share/Markdown-Document/listing-ssetup.tex -o "$outfile" "$file"
 
     done
 }
