bash alive again, and shining more than ever

diff --git a/installSkelFiles2home b/installSkelFiles2home
--- a/installSkelFiles2home
+++ b/installSkelFiles2home
@@ -34,18 +34,35 @@ readonly _app=$(basename $0)
 readonly _appDir=$(dirname $0)
 readonly _absoluteAppDir=$(cd $_appDir; /bin/pwd)
 readonly _appVersion="0.0.1" # use semantic versioning
-DebugFlag=FALSE
-VerboseFlag=FALSE
+export DebugFlag=${DebugFlag:-FALSE}
+export VerboseFlag=${VerboseFlasg:-FALSE}
 
 #########################################################################################
 # FUNCTIONS
+###################################### 
+# Skeleton functions, considered RO. v0.4.1
+
+# so helps to write a message in reverse mode
+function so()
+# always show such a message.  If known terminal, print the message
+# in reverse video mode. This is the other way, not using escape sequences
+{
+   [ "$1" != on -a "$1" != off ] && return 
+    if [ "$TERM" = xterm -o "$TERM" = vt100 -o "$TERM" = xterm-256color  -o "$TERM" = screen ] ; then
+      [ "$1" = on ] && tput smso 
+      [ "$1" = off ] && tput rmso
+    fi
+}
 
 # --- debug: Conditional debugging. All commands begin w/ debug.
 
 function debugSet()             { DebugFlag=TRUE; return 0; }
 function debugUnset()           { DebugFlag=; return 0; }
-function debugExecIfDebug()     { [ $DebugFlag = TRUE ] && $*; return 0; }
-function debug()                { [ $DebugFlag = TRUE ] && err 'DEBUG:' $* 1>&2 ; return 0; }
+function debugExecIfDebug()     { [ "$DebugFlag" = TRUE ] && $*; return 0; }
+function debug()                { [ "$DebugFlag" = TRUE ] && echo 'DEBUG:'$* 1>&2 ; return 0; }
+function debug4()               { [ "$DebugFlag" = TRUE ] && echo 'DEBUG:    ' $* 1>&2 ; return 0; }
+function debug8()               { [ "$DebugFlag" = TRUE ] && echo 'DEBUG:        ' $* 1>&2 ; return 0; }
+function debug12()              { [ "$DebugFlag" = TRUE ] && echo 'DEBUG:            ' $* 1>&2 ; return 0; }
 
 function verbose()              { [ "$VerboseFlag" = TRUE ] && echo -n $* ; return 0; }
 function verbosenl()            { [ "$VerboseFlag" = TRUE ] && echo $* ; return 0; }
@@ -59,16 +76,22 @@ function colBlink()     { printf "\e[5m"; return 0; }
 
 # --- Exits
 
-# always show such a message.  If known terminal, print the message
-# in reverse video mode. This is the other way, not using escape sequences
-function soErr() { err $*; }
+# function error()        { err 'ERROR:' $*; return 0; } # similar to err but with ERROR prefix and possibility to include 
+# Write an error message to stderr. We cannot use err here as the spaces would be removed.
+function error()        { so on; echo 'ERROR:'$* 1>&2;            so off ; return 0; }
+function error4()       { so on; echo 'ERROR:    '$* 1>&2;        so off ; return 0; }
+function error8()       { so on; echo 'ERROR:        '$* 1>&2;    so off ; return 0; }
+function error12()      { so on; echo 'ERROR:            '$* 1>&2;so off ; return 0; }
 
-function error()        { soErr 'ERROR:' $*; return 0; } # similar to err but with ERROR prefix and reverse colour (curses).
-function errorExit()    { EXITCODE=$1 ; shift; error $* 1>&2; exit $EXITCODE; }
+function warning()      { so on; echo 'WARNING:'$* 1>&2;          so off; return 0; }
+
+function errorExit()    { EXITCODE=$1 ; shift; error $* ; exit $EXITCODE; }
 function exitIfErr()    { a="$1"; b="$2"; shift; shift; [ "$a" -ne 0 ] && errorExit $b App returned $b $*; }
-function err()          { echo $* 1>&2; } # just write to stderr
-function err4()          { echo '   ' $* 1>&2; } # just write to stderr
-function err8()          { echo '       ' $* 1>&2; } # just write to stderr
+
+function err()          { echo $* 1>&2; }                 # just write to stderr
+function err4()         { echo '   ' $* 1>&2; }           # just write to stderr
+function err8()         { echo '       ' $* 1>&2; }       # just write to stderr
+function err12()        { echo '           ' $* 1>&2; }   # just write to stderr
 
 # --- Existance checks
 function exitIfBinariesNotFound()       { for file in $@; do [ $(command -v "$file") ] || errorExit 253 binary not found: $file; done }
