git gee version 3 implementing git gee doctor to fix gitignore, if files under git gee were moved

diff --git a/bin/git/gee b/bin/git/gee
--- a/bin/git/gee
+++ b/bin/git/gee
@@ -44,7 +44,7 @@
 # shellcheck disable=SC2155
 readonly _app=$(basename "${0}")
 readonly _appDir=$(dirname "$(readlink -f "${0}")")
-readonly _appVersion="2.4.0" # use semantic versioning
+readonly _appVersion="3.0.0" # use semantic versioning # ALSO CHANGE THE PRECOMMIT FILE TO CONTAIN THE SAME VERSION NUMBER
 export DebugFlag=${DebugFlag:-FALSE}
 
 #########################################################################################
@@ -196,6 +196,74 @@ function tempDir() { mktemp -d "${TMPDIR:-/tmp/}$_app.YYYYYYYYY"; }
 
 # application-specific functions  ===============================================================================
 
+function git-root-relative-path() {
+    initDefaultVars
+    local _absfile
+    [ -z "$1" ] && errorExit 90 "missing argument to git-root-relative-path"
+    local -r _absfile="$(readlink -f "$1")"
+    # shellcheck disable=SC2001
+    #echo absfile $_absfile
+    #echo gitroot $gitroot
+    echo "$_absfile" | sed "s,$gitroot/,,"
+}
+
+function exitIfNotInGitRepo() {
+    git rev-parse --show-toplevel &>/dev/null || errorExit 11 "Not in a git repository"
+}
+
+function mtime() {
+    ## mtime, return modification time of a file in epoch, UTC
+    [ -z "$1" ] && errorExit 80 "mtime, no argument specified"
+    [ ! -e "$1" ] && errorExit 81 "mtime, argument not a file"
+    date -u -r "$1" +%s # OK for OSX, Linux
+}
+
+function mtimeSet() {
+    ## mtimeSet, set the modification time of a file in epoch, UTC
+    [ -z "$1" ] && errorExit 85 "mtimeSet, no argument specified"
+    local -r _time=$1
+    [ ! -e "$2" ] && errorExit 86 "mtimeSet, argument not a file"
+
+}
+
+# doctor fixes .gitignore by adding entries for files in .gitignore that were moved in between.
+# It does so by just adding new, additional entries. It does neither delete or change existing entries.
+# By this it helps to make sure that you do not accidentally add confidential files to the git repository in an
+# unencrypted manner.
+function doctor() {
+    exitIfNotInGitGeeRepo
+    initDefaultVars
+
+    # handle CLI options, dry mode implies verbose mode, -- finishes 
+    _dryMode=
+    while true; do
+        [ "$1"  = '-n' ] || [ "$1" = '--dry' ] && _dryMode=echo && 1>&2 echo DRY mode && verboseSet && shift && continue
+        [ "$1"  = '-v' ] || [ "$1" = '--verbose' ] && verboseSet && 1>&2 echo verbose && shift && continue
+        [ "$1" = '--' ] && shift && break   # break could be omitted, but so it is easier to read and more safe if the code will be changed.
+        break
+    done
+    [ $# -gt 0 ]&& errorExit 90 "No argument supported"     # was thinking to allow us to specify sub-directory. But, how do we check that this arg specifies a *sub*-directory easily? 
+
+    cd "$gitroot" || errorExit 91 'git doctor; cannot change CWD to gitroot:'"$gitroot"
+    find "." -type f -name '*.gee' -print0 | while IFS= read -r -d '' file; do
+        # Inside the loop, you can perform actions on each file
+        srcFile="$(echo "$file" | sed 's,.gee$,,' | sed 's,^\./,/,')"
+        #suffix="$(echo "$srcFile" | sed 's,.*\.,.,')"
+        verbose "Processing src-file:$srcFile:"
+        # Currently, we do not check if a wildcard line also ignores a file put under git gee as git gee a normally adds individual entries
+        # for each file in .gitignore
+        # You can replace this echo statement with whatever action you want to perform on each file
+        # For example, you could process the file contents, move or copy the file, etc.
+        if $(grep "$srcFile" .gitignore > /dev/null) ; then 
+            verbosenl file found
+        else
+            verbosenl file NOT found
+            [ -n "$_dryMode" ] && echo "echo $srcFile >> .gitignore"
+            [ -z "$_dryMode" ] && echo "$srcFile" >> .gitignore
+        fi
+    done
+}
+
 # shellcheck disable=all
 function usage() {
     err DESCRIPTION
@@ -220,9 +288,13 @@ function usage() {
     err8 delete the unencrypted versions of gee files if they are older than the correspondig gee files.
     err8 In force mode, delete the unencrypted files even if they are younger thane the correspondig gee files.
     err
-    err4 $_app '( u[n[e[n[c[r[y[p[t]]]]]]]] | d[e[c[r[y[p[t]]]]]] )' '<<file>> ...'
-    err8 - creates an unencrypted version of the file. If no argument is given, it does so for all .gee files.
-    err8 - No difference if the file is specified with .gee or without it.
+    err4 $_app '( doc | doctor )'
+    err8 '- for every source file under .gee, check if the source file (without .gee) is under .gitignore'
+    err8 '- If the source file is not found in .gitignore, add it to it.'
+    err
+    err4 $_app '( u[n[e[n[c[r[y[p[t]]]]]]]] | d[e[c[r[y[p[t]]]]]] ) <<file>> ...'
+    err8 '- creates an unencrypted version of the file. If no argument is given, it does so for all .gee files.'
+    err8 '- No difference if the file is specified with .gee or without it.'
     err
     err4 $_app 'e[n[c[r[y[p[t]]]]]]' '[ -f | --force ] <<file>> ...'
     err8 todo force mode?
@@ -251,34 +323,6 @@ function usage() {
     err8 '-D      ::= enable debug output'
     err8 '-v      ::= verbose mode'
     err8 '-h      ::= show usage message and exit with exit code 1'
-}
-
-function git-root-relative-path() {
-    initDefaultVars
-    local _absfile
-    [ -z "$1" ] && errorExit 90 "missing argument to git-root-relative-path"
-    local -r _absfile=$(readlink -f "$1")
-    # shellcheck disable=SC2001
-    echo "$_absfile" | sed "s,$gitroot/,,"
-}
-
-function exitIfNotInGitRepo() {
-    git rev-parse --show-toplevel &>/dev/null || errorExit 11 "Not in a git repository"
-}
-
-function mtime() {
-    ## mtime, return modification time of a file in epoch, UTC
-    [ -z "$1" ] && errorExit 80 "mtime, no argument specified"
-    [ ! -e "$1" ] && errorExit 81 "mtime, argument not a file"
-    date -u -r "$1" +%s # OK for OSX, Linux
-}
-
-function mtimeSet() {
-    ## mtimeSet, set the modification time of a file in epoch, UTC
-    [ -z "$1" ] && errorExit 85 "mtimeSet, no argument specified"
-    local -r _time=$1
-    [ ! -e "$2" ] && errorExit 86 "mtimeSet, argument not a file"
-
 }
 
 #############################################################################################
@@ -336,7 +380,7 @@ function createPreCommit() {
     # single-quotes around ENDINIT prevents evaluation of vars inside here document
     cat >|.git/hooks/pre-commit <<'ENDINIT'
 #!/usr/bin/env bash
-# gee:version:2.4.0
+# gee:version:3.0.0
 # --- debug: Conditional debugging. All commands begin w/ debug.
 function debugSet() {
     DebugFlag=TRUE
@@ -622,18 +666,18 @@ function listMode() {
 function checkGeeVersions() {
     local commit_version=''
     initDefaultVars
-    [ ! -f "$gitroot/.git/hooks/pre-commit" ] && \
-        1>&2 echo 'no pre-commit is installed. Consider running git gee init?' && exit 20
-    commit_version=$(grep  '# gee:version:' "$gitroot/.git/hooks/pre-commit")
-    [ -z "$commit_version" ] && \
-        1>&2 echo 'Cannot determine version of the pre-commit hook. Consider a reinstall using git init?' &&
+    [ ! -f "$gitroot/.git/hooks/pre-commit" ] &&
+        echo 1>&2 'no pre-commit is installed. Consider running git gee init?' && exit 20
+    commit_version=$(grep '# gee:version:' "$gitroot/.git/hooks/pre-commit")
+    [ -z "$commit_version" ] &&
+        echo 1>&2 'Cannot determine version of the pre-commit hook. Consider a reinstall using git init?' &&
         exit 21
     commit_version=$(echo "$commit_version" | sed 's/.*://')
     debug commit_version is: "$commit_version"
-    [ "$commit_version" != "$_appVersion" ] && \
-        1>&2 echo pre-commit hook version is: "$commit_version" && \
-        1>&2 echo "git gee version is: $_appVersion" && \
-        1>&2 echo "Please align" && exit 22
+    [ "$commit_version" != "$_appVersion" ] &&
+        echo 1>&2 pre-commit hook version is: "$commit_version" &&
+        echo 1>&2 "git gee version is: $_appVersion" &&
+        echo 1>&2 "Please align" && exit 22
 }
 
 #############################################################################################
@@ -663,11 +707,16 @@ function main() {
         checkGeeVersions
         listMode "$@" # created dependency by gee s
         ;;
+    doc | doctor)
+        checkGeeVersions
+        shift
+        doctor "$@"
+        ;;
     e | en | enc | encr | encry | encryp | encrypt | encrypted)
         checkGeeVersions
         encryptMode "$@"
         ;;
-    d | de | dec | decr | decry | decryp | decrypt | u | un | une | unen | unencr | unencry | unencryp | unencrypt)
+    de | dec | decr | decry | decryp | decrypt | u | un | une | unen | unencr | unencry | unencryp | unencrypt)
         checkGeeVersions
         decryptMode "$@"
         ;;
@@ -675,7 +724,7 @@ function main() {
         checkGeeVersions
         git gee l | grep -E --color ', modified\)$' # must be changed if the output format of l is changed
         ;;
-    version)
+    ver | version)
         echo $_appVersion
         exit 0
         ;;
